export const FLAGS = {
  USE_BABEL_FLAG: 'USE_BABEL',
  MAKE_TESTS_FLAG: 'MAKE_TESTS',
  USE_MOCHA_FLAG: 'USE_MOCHA',
  USE_AVA_FLAG: 'USE_AVA',
  CODE_COVERAGE_FLAG: 'CODE_COVERAGE',
  CODE_COVERAGE_ISTANBUL_FLAG: 'CODE_COVERAGE_ISTANBUL_FLAG',
  CODE_COVERAGE_NYC_FLAG: 'CODE_COVERAGE_NYC_FLAG',
  SHOULD_LINT_FLAG: 'SHOULD_LINT',
  LOCK_DEPENDENCIES_FLAG: 'LOCK_DEPENDENCIES',
  LOCK_DEPENDENCIES_YARN_FLAG: 'LOCK_DEPENDENCIES_YARN',
  LOCK_DEPENDENCIES_SHRINKWRAP_FLAG: 'LOCK_DEPENDENCIES_SHRINKWRAP',
  BUILD_EXAMPLE_FLAG: 'BUILD_EXAMPLE'
};

export default FLAGS;
